### ISSUE TITLE
Plugin ID Mismatch

### ISSUE THREAD

**Issue by mAAdhaTTah** [cwfryer/obsidian-callout-suggestions#1]
I saw this get merged and wanted to use it but attempting to install it, I get a "Plug ID Mismatch" error. My guess is you had to change the `id` to remove `obsidian` but haven't published an updated version, so Obsidian is trying to grab the previous release from the Releases and seeing a mismatch. Can you publish a new version?

**Comment by looneyapache** [comment]
Same Issue

**Comment by connradolisboa** [comment]
same

**Comment by cwfryer** [comment]
Should be fixed. I just revised the existing published version with the correct manifest.json

@mAAdhaTTah Let me know if it's fixed for you

**Comment by mAAdhaTTah** [comment]
Nope, still getting the same error.

**Comment by cwfryer** [comment]
@mAAdhaTTah 
I created a new release that seems to solve the problem.
I successfully installed it in a fresh vault after finally reproducing the error you saw.
Hopefully it's fixed now.

**Comment by mAAdhaTTah** [comment]
Works for me, thanks!
