### ISSUE TITLE
Trigger for the ! character does not function

### ISSUE THREAD

**Issue by solarisjon** [cwfryer/obsidian-callout-suggestions#3]
Obsidian Version 1.5.12 (Installer 1.4.16)
Callout Manager : 1.0.1
Callout Suggestions :  1.0.0
Mac OSx : 14.4.1

Trigger the auto-complete with >! does not function other triggers such as @ for the natural language date plugin do work,.

**Comment by cwfryer** [comment]
This is the block of code that handles the trigger from [src/suggest/callout-suggest.ts](https://github.com/cwfryer/obsidian-callout-suggestions/blob/8344148494590f0599b0e2b34674525ca136dd2e/src/suggest/callout-suggest.ts#L99-L116)

```TypeScript
onTrigger(cursor: EditorPosition, editor: Editor, _file: TFile | null): EditorSuggestTriggerInfo | null {
	const triggerPhrase = this.plugin.settings.autocompleteTriggerPhrase;
	const startPos = this.context?.start || {
		line: cursor.line,
		ch: cursor.ch - triggerPhrase.length - 1
	}

	if (!editor.getRange(startPos, cursor).startsWith(">" + triggerPhrase)) {
		return null
	}

	return {
		start: startPos,
		end: cursor,
		query: editor.getRange(startPos, cursor).substring(triggerPhrase.length)
	}
}
```

All it does is find where you're at in the line, go backwards by by the length of your trigger phrase, then go back one more to cover the > character. If that fails, it goes back to the start of the line and checks there.

If that range starts with > followed immediately by your trigger phrase, it runs the suggest modal.

I don't have a Mac, so I can't reproduce your environment. I use the plugin on Linux, Windows, and Android and it's working fine for me on all of them.

If you want to go mess around with how the trigger works in the compiled main.js file in your .obsidian/plugins folder, it's the block on lines 876 to 891.

**Comment by ptsouchlos** [comment]
I'm having the same issue on Windows 11:

Obsidian Version: 1.6.1
Callout Manager: `1.0.1`
Callout Suggestions: `1.0.0`

The natural language `@` trigger works, but `>!` does not work.
