### ISSUE TITLE
Suggestion does not contain custom created callouts

### ISSUE THREAD

**Issue by tahamandviwala4** [cwfryer/obsidian-callout-suggestions#4]
Callout suggestion only contains obsidian default callout and **does not suggest the custom-created callouts.**
![image](https://github.com/cwfryer/obsidian-callout-suggestions/assets/60511036/ce794511-067c-4191-b5d0-0bd8232ec21f)
image from the callout manager plugin.

![image](https://github.com/cwfryer/obsidian-callout-suggestions/assets/60511036/dc1714d1-9a45-4640-869d-acd3948427b0)
callout suggestions do not contain custom-callout.

Thanks for the plugin :)

**Comment by cwfryer** [comment]
Possibly related to this? [obsidian-callout-manager #15](https://github.com/eth-p/obsidian-callout-manager/issues/15)

If you just type the callout in using the base syntax does it work?
```markdown
> [!Created Notes]
> yada yada yada
```

**Comment by tahamandviwala4** [comment]
do you mean this "`>[! ]`" by base syntax?
if yes, suggestions do not appear.

**Comment by tahamandviwala4** [comment]
There must be a problem with the callout-manager plugin API. It doesn't return the custom created callouts.

**Comment by cwfryer** [comment]
Can you get the custom callout to even render if you type it in manually?

**Comment by tahamandviwala4** [comment]
> Can you get the custom callout to even render if you type it in manually?

Yes

**Comment by cwfryer** [comment]
If you look at the callout-manager API it seems to me that it adds custom callouts (e.g. ones created within the plugin) to the collection after initializing all of the other callout sources (builtin, theme, snippets, etc.)
```typescript
		// Create the callout collection.
		// Use getCalloutProperties to resolve the callout's color and icon.
		this.callouts = new CalloutCollection((id) => {
			const { icon, color } = this.calloutResolver.getCalloutProperties(id);
			console.debug('Resolved Callout:', id, { icon, color });
			return {
				id,
				icon,
				color,
			};
		});


		// Add the custom callouts.
		this.callouts.custom.add(...settings.callouts.custom);
```
[source](https://github.com/eth-p/obsidian-callout-manager/blob/d425fd450cd06bb776bd04826e5c97d7ffad5407/src/main.ts#L44-L57)

The API function for getCallouts is just a call to this.plugin.callouts.values() getting the values of the above defined collection. Based on the above definition, you'd expect to see the callouts at the very bottom of the suggestion modal.

In the code for callout-manager's settings UI it does a comparison function to sort by icon ([here](https://github.com/eth-p/obsidian-callout-manager/blob/d425fd450cd06bb776bd04826e5c97d7ffad5407/src/panes/select-icon-pane.ts#L67)) so you'll see a different sorting order in the settings UI vs the API call results.

After a fresh install of both plugins, I can find custom ones all the way at the bottom of the list:
![Screenshot from 2024-06-05 12-54-29](https://github.com/cwfryer/obsidian-callout-suggestions/assets/48137894/4347208d-fc05-43e2-a251-8010485de2f3)

You can try fuzzy finding your custom callouts with something like:

```markdown
>!notes
```

**Comment by tahamandviwala4** [comment]
> If you look at the callout-manager API it seems to me that it adds custom callouts (e.g. ones created within the plugin) to the collection after initializing all of the other callout sources (builtin, theme, snippets, etc.)

This works for me.
Thanks for helping :)
