### ISSUE TITLE
Ordering Callouts

### ISSUE THREAD

**Issue by ThisUserNeedsHelp** [cwfryer/obsidian-callout-suggestions#5]
The callout which I will probably want to use most frequently is at the bottom of the Callout Suggestions menu. Is there a way to move it to the top?

**Comment by cwfryer** [comment]
This plugin relies on the another plugin [callout-manager](https://github.com/eth-p/obsidian-callout-manager) to produce the suggestion menu.

All it does it make a call to their API to return the Callouts for the suggestion modal. So the order is set by their API, and theirs currently doesn't support any kind of passable arguments to sort the results.

If you wanted the exact last one on top, you could add a line something like this into my plugin's main.js file, right after line 831:

```javascript
  getCalloutSuggestions(context) {
    let needle = context.query;
    let callouts = this.plugin.calloutManager.getCallouts();
    callouts = callouts.reverse(); //<--------------------------- Add this line here
    let haystack = (callouts == null ? void 0 : callouts.map((callout) => callout.id)) || [needle];
    let uf = new uFuzzy({});
    let idxs = uf.filter(haystack, needle);

```

You could also use a sort function to sort it however you think is fitting:
```javascript
  getCalloutSuggestions(context) {
    let needle = context.query;
    let callouts = this.plugin.calloutManager.getCallouts();
    callouts = callouts.sort((a,b) => {if a.label < b.label return 1 else return -1}); //<--------------------------- Add this line here
    let haystack = (callouts == null ? void 0 : callouts.map((callout) => callout.id)) || [needle];
    let uf = new uFuzzy({});
    let idxs = uf.filter(haystack, needle);

```

Hope this helps!

**Comment by ThisUserNeedsHelp** [comment]
Thank You
