### ISSUE TITLE
[Feature Request] Add Casing Option to Suggestions

### ISSUE THREAD

**Issue by ykis-0-0** [cwfryer/obsidian-callout-suggestions#7]
Hi, Is it viable to add an option to set the casing of the callout tag inserted?

It'll probably be a dropdown menu to select between something like these:
* Lowercase (`[!example]`)
* Titlecase (`[!Example]`)
* Uppercase (`[!EXAMPLE]`)

**Comment by cwfryer** [comment]
Added in [1d29a4a](https://github.com/cwfryer/obsidian-callout-suggestions/commit/1d29a4a5e38f29719691222c2930fd0365057727).

Released as [1.0.2](https://github.com/cwfryer/obsidian-callout-suggestions/releases/tag/1.0.2)
